```{r, echo = FALSE, results = "hide"}
v1 <- sample(10:50, 1) # speed of first phase in km/h
d1 <- sample(10:50, 1) # distance of first phase in km

v2 <- sample(80:120, 1) # speed of second phase in km/h
d2 <- sample(100:300, 1) # distance of second phase in km

ans <- signif((d1 + d2)/(d1/v1 + d2/v2), 2)
sc <- num_to_schoice(ans, delta = 2, digits = 0, range = c(v1, v2), format = FALSE)

sc$questions <- sprintf("\\SI{%g}{km/h}", sc$questions)
```

Question
========
A car travels \SI{`r d1`}{km} at \SI{`r v1`}{km/h} and \SI{`r d2`}{km} at \SI{`r v2`}{km/h}. What is the average speed for this trip?

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(sc$questions, markup = "markdown")
```

Solution
========
The average speed is the total distance divided by the total time.

$$ v_{avg} = \frac{d_{total}}{t_{total}} = \frac{d_1 + d_2}{d_1/v_1 + d_2/v_2} = \frac{\SI{`r d1`}{km} + \SI{`r d2`}{km}}{\frac{\SI{`r d1`}{km}}{\SI{`r v1`}{km/h}} + \frac{\SI{`r d2`}{km}}{\SI{`r v2`}{km/h}}} = \SI{`r ans`}{km/h}$$

Meta-information
================
exname: calculate average speed given speeds and distances of two stages
extype: schoice
exsolution: `r mchoice2string(sc$solutions)`
exshuffle: 4
