```{r, echo = FALSE, results = "hide"}
sf <- 3 # significant figures to use
v1 <- sample(20:50, 1) # speed of first phase in km/h
t1 <- sample(1:3, 1) # time of first phase in h

v2 <- sample(80:120, 1) # speed of second phase in km/h
t2 <- sample(8:12, 1) # time of second phase in h

ans <- (v1*t1 + v2*t2)/(t1 + t2)
dis <- c((v1 + v2)/2)

sc <- num_to_schoice(ans, wrong = dis, delta = 0.6, range = c(v1, v2), format = FALSE)
sc$questions <- sapply(sc$questions, signif, sf)
sc$questions <- sprintf("\\SI{%g}{km/h}", sc$questions)
```

Question
========
A truck travels at \SI{`r v1`}{km/h} for \SI{`r t1`}{hours} and at \SI{`r v2`}{km/h} for \SI{`r t2`}{hours}. What is the average speed for the trip?

```{r questionlist, echo = FALSE, results = "asis"}
answerlist(sc$questions, markup = "markdown")
```

Solution
========
The average speed is the total distance divided by the total time.

$$ v_{avg} = \frac{d_{total}}{t_{total}} = \frac{v_1 t_1 + v_2 t_2}{t_1 + t_2} = \frac{(\SI{`r v1`}{km/h}) (\SI{`r t1`}{h}) + (\SI{`r v2`}{km/h})(\SI{`r t2`}{h})}{\SI{`r t1`}{h} + \SI{`r t2`}{h}} = \SI{`r signif(ans, sf)`}{km/h}$$

Meta-information
================
exname: calculate average speed given speeds and times of two stages
extype: schoice
exsolution: `r mchoice2string(sc$solutions)`
exshuffle: 4
