```{r, echo = FALSE, results = "hide"}
k <- 9e9 # N m^2 / C^2
q <- signif(runif(1, 2, 9.99), 2) # charges (nanocoulombs)
r <- sample(10:50, 1) # distance (cm)

ans <- k * q[1] * 1e-9 / (r / 100)^2  # coulomb force (N)

sc <- num_to_schoice(ans, delta = ans/10, range = c(0.1, 10) * ans, format = FALSE, digits = 5)
sc$questions <- sprintf("%g N/C", signif(sc$questions, 2))
```
Question
========
What is the electric field strength $`r r` \,\mathsf{cm}$ away from a 
$+`r q` \,\mathsf{nC}$ point charge?

```{r, echo = FALSE, results = "asis"}
answerlist(sc$questions, markup = "markdown")
```

Solution
========
The electric field from a point charge is

$$E = \frac{k q}{r^2} = \frac{(9.0\times 10^9 \mathsf{\,N\,m^2 / C^2})(
`r q` \times 10^{-9} \mathsf{\,C})}{(`r r` \times 10^{-2} \mathsf{\,m})^2}
= `r signif(ans, 2)` \mathsf{\,N/C}$$


Meta-information
================
exname: Calculate Electric Field from Point Charge
extype: schoice
exsolution: `r mchoice2string(sc$solutions)`
exshuffle: 4

